# Generated by Django 6.0 on 2026-01-21 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.panchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.panchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Replied', 'Replied')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.farmer')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.officer')),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.panchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doubts.doubt')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.officer')),
            ],
        ),
    ]
