# Generated by Django 6.0 on 2026-01-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerprofile'),
        ('doubts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile'),
        ),
        migrations.RemoveField(
            model_name='officer',
            name='panchayat',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='officer',
        ),
        migrations.AlterField(
            model_name='doubt',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.officerprofile'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='panchayat',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='reply',
            name='doubt',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.DeleteModel(
            name='Panchayat',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
