# Generated by Django 6.0 on 2026-01-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('autumn', 'autumn'), ('winter', 'Winter'), ('spring', 'Spring')], max_length=20)),
                ('soil_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
