# Generated by Django 6.0 on 2026-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='duration',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
