# Generated by Django 6.0 on 2026-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertilixer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Monsoon', 'Monsoon'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=20),
        ),
    ]
