# Generated by Django 6.0 on 2026-01-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_fertilixer_alter_crop_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical'), ('bio', 'Bio-fertilizer')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fertilixer',
        ),
        migrations.CreateModel(
            name='CropFertilizerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.fertilizer')),
            ],
        ),
    ]
