# Generated by Django 6.0.2 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_fertilizer_remove_crop_fertilixer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
