# Generated by Django 6.0.2 on 2026-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
