# Generated by Django 6.0 on 2026-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='government_scheme',
            name='scheme_pdf',
            field=models.FileField(blank=True, null=True, upload_to='scheme_pdfs/'),
        ),
    ]
