# Generated by Django 6.0 on 2026-01-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_course_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content_url',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_notes/'),
        ),
    ]
