# Generated by Django 6.0 on 2026-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_rename_content_url_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
