# Generated by Django 6.0 on 2026-01-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0006_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government_scheme',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
