# Generated by Django 6.0 on 2026-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/'),
        ),
    ]
