# Generated by Django 6.0 on 2026-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplaceitem_contact_phone_marketplaceitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitem',
            name='category',
            field=models.CharField(choices=[('Crop', 'Crop'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Seeds', 'Seeds'), ('Produce', 'Produce')], max_length=20),
        ),
    ]
