# Generated by Django 6.0.2 on 2026-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplaceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='unit',
            field=models.CharField(default='kg', help_text='e.g., kg, bunch, gram', max_length=10),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
