# Generated by Django 6.0 on 2026-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('officer', 'Krishi Officer'), ('customer', 'Customer'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
    ]
