# Generated by Django 6.0.2 on 2026-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='officer_ids/'),
        ),
    ]
