# Generated by Django 6.0.2 on 2026-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmerdoubt_delete_farmerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
